---
- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: nginx systemd restart
  systemd:
    name: nginx
    state: started
    daemon_reload: yes

- name: nginx restart
  service:
    name=nginx
    state=restarted

- name: nginx reload
  service:
    name=nginx
    state=reloaded
