---
- name: Install PHP
  yum: name=php state=latest

- name: Install PHP packages
  become: true
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - php-curl
    - php-fpm
    - php-intl
    - php-mysql
    - php-xml
    - php-mbstring
  notify: 
    - Restart PHP-FPM
